### ISSUE TITLE
Help fix broken Place Bet view

### ISSUE THREAD

**Issue by Jnrlouis** [Jnrlouis/BoardMan#6]
Please this request is of a higher priority as it is a core feature. The view of the "Enter" bet is broken. I can't figure out how to fix it properly. Help!

Check this link to see what I mean, or you could just attempt to place a bet on one of the open public events on the app.
Link: https://i.imgur.com/HlY1NsD.jpg && https://i.imgur.com/LaKzYWW.jpg

**Comment by ibmeshach** [comment]
done
